import React, { cloneElement, isValidElement, type ComponentProps, type ReactElement, type ReactNode } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type DimensionValue, type ViewStyle } from "react-native";
import { useTheme } from "../theme/ThemeProvider";

type ChildProps = { style?: unknown; accessibilityLabel?: string; accessibilityState?: object; nativeID?: string; "aria-describedby"?: string };
const webFocus: ViewStyle = { outlineStyle: "solid", outlineWidth: 2, outlineColor: "#40916c", outlineOffset: 2 };

export type ButtonProps = Omit<ComponentProps<typeof Pressable>, "children"> & { label: string; variant?: "primary" | "secondary" | "quiet" | "icon" | "danger"; loading?: boolean; icon?: ReactNode };
export function Button({ label, variant = "primary", loading = false, disabled, icon, style, onPress, ...props }: ButtonProps) {
  const { theme } = useTheme();
  const colors = theme.colors;
  const bg = variant === "primary" ? colors.accent : variant === "danger" ? colors.danger : variant === "secondary" ? colors.surface : "transparent";
  const fg = variant === "primary" || variant === "danger" ? colors.accentContrast : colors.text;
  return <Pressable {...props} onPress={disabled || loading ? undefined : onPress} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: disabled || loading, busy: loading }} disabled={disabled || loading} focusable style={({ pressed }) => { const customStyle = typeof style === "function" ? style({ pressed }) : style; return [styles.button, { backgroundColor: bg, borderColor: variant === "quiet" ? "transparent" : colors.border, opacity: pressed ? 0.76 : 1 }, variant === "icon" && styles.iconButton, customStyle, webFocus]; }}><>{loading ? <ActivityIndicator color={fg} /> : icon}{variant !== "icon" && <Text style={[styles.buttonText, { color: fg, fontSize: theme.type.body }]}>{label}</Text>}</></Pressable>;
}

export type FieldProps = { label: string; hint?: string; error?: string; control: ReactElement<ChildProps> };
export function Field({ label, hint, error, control }: FieldProps) {
  const id = `field-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  const describedBy = `${id}-description`;
  const controlProps: ChildProps = { nativeID: id, accessibilityLabel: label, accessibilityState: { invalid: !!error }, "aria-describedby": describedBy };
  return <View style={styles.field}><Text nativeID={`${id}-label`} style={styles.label}>{label}</Text>{isValidElement(control) ? cloneElement(control, controlProps) : control}{(hint || error) && <Text nativeID={describedBy} style={[styles.hint, error && styles.error]}>{error || hint}</Text>}</View>;
}

export type TextAreaProps = Omit<ComponentProps<typeof TextInput>, "style"> & { label: string; hint?: string; error?: string };
export function TextArea({ label, hint, error, ...props }: TextAreaProps) { return <Field label={label} hint={hint} error={error} control={<TextInput {...props} multiline textAlignVertical="top" style={styles.textarea} />} />; }

export function Screen({ children, ...props }: ComponentProps<typeof ScrollView>) { const { theme } = useTheme(); return <ScrollView {...props} contentContainerStyle={[styles.screen, { padding: theme.spacing.md }]}><View style={[styles.readable, { maxWidth: 1120 }]}>{children}</View></ScrollView>; }
export function PageHeader({ title, subtitle, actions }: { title: string; subtitle?: string; actions?: ReactNode }) { const { theme } = useTheme(); return <View style={styles.pageHeader}><View style={{ flex: 1 }}><Text accessibilityRole="header" style={[styles.heading, { color: theme.colors.text, fontSize: theme.type.heading }]}>{title}</Text>{subtitle && <Text style={[styles.hint, { color: theme.colors.mutedText }]}>{subtitle}</Text>}</View>{actions}</View>; }
export function Section({ title, children, ...props }: ComponentProps<typeof View> & { title?: string }) { const { theme } = useTheme(); return <View {...props} style={[{ marginBottom: theme.spacing.lg }, props.style]}>{title && <Text accessibilityRole="header" style={[styles.sectionTitle, { color: theme.colors.text }]}>{title}</Text>}{children}</View>; }
export function ResponsiveGrid({ children, minItemWidth = 260, ...props }: ComponentProps<typeof View> & { minItemWidth?: number }) { return <View {...props} style={[styles.grid, props.style]}>{React.Children.map(children, child => <View style={{ flexGrow: 1, flexBasis: minItemWidth }}>{child}</View>)}</View>; }
export function InlineNotice({ message, tone = "info" }: { message: string; tone?: "info" | "success" | "warning" | "error" }) { const { theme } = useTheme(); return <View accessibilityRole="alert" style={[styles.notice, { borderColor: theme.colors.border }]}><Text style={{ color: tone === "error" ? theme.colors.danger : theme.colors.text }}>{message}</Text></View>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <View style={styles.state}><Text accessibilityRole="header" style={styles.stateTitle}>{title}</Text>{description && <Text style={styles.hint}>{description}</Text>}{action}</View>; }
export function LoadingState({ label = "Loading" }: { label?: string }) { return <View accessibilityRole="progressbar" accessibilityLabel={label} style={styles.state}><ActivityIndicator /><Text style={styles.hint}>{label}</Text></View>; }
export function ErrorState({ title = "Something went wrong", description, action }: { title?: string; description?: string; action?: ReactNode }) { return <View accessibilityRole="alert" style={styles.state}><Text accessibilityRole="header" style={styles.stateTitle}>{title}</Text>{description && <Text style={styles.hint}>{description}</Text>}{action}</View>; }
export function OfflineBanner({ message = "You’re offline. Changes will sync when you reconnect." }: { message?: string }) { return <InlineNotice message={message} tone="warning" />; }
export function StatusBadge({ status, label }: { status: "success" | "warning" | "error" | "info" | string; label?: string }) { const { theme } = useTheme(); return <View accessibilityRole="text" aria-live="polite" style={[styles.badge, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Text style={{ color: theme.colors.text }}>{label || status}</Text></View>; }

export type ImportStatus = "queued" | "processing" | "completed" | "review_required" | "failed" | "cancelled" | "timed_out";
const importLabels: Record<ImportStatus, string> = { queued: "Waiting", processing: "Working", completed: "Complete", review_required: "Review needed", failed: "Failed", cancelled: "Cancelled", timed_out: "Timed out" };
export function ImportProgress({ status }: { status: ImportStatus }) { return <View testID="import-progress" accessibilityRole="text" aria-live="polite" accessibilityLabel={`Import status: ${importLabels[status]}`} style={styles.state}><Text testID="import-progress-label">{importLabels[status]}</Text></View>; }
export function RatingControl({ value, onChange, max = 5 }: { value: number; onChange: (value: number) => void; max?: number }) { return <View accessibilityRole="radiogroup" accessibilityLabel="Rating"><View style={styles.rating}>{Array.from({ length: max }, (_, index) => { const rating = index + 1; return <Pressable key={rating} accessibilityRole="button" accessibilityLabel={`Rate ${rating} out of ${max}`} accessibilityState={{ selected: rating === value }} onPress={() => onChange(rating)} focusable style={[styles.ratingButton, webFocus]}><Text>{rating <= value ? "★" : "☆"}</Text></Pressable>; })}</View></View>; }
export function Toast({ message, visible = true }: { message: string; visible?: boolean }) { if (!visible) return null; return <View accessibilityRole="alert" style={styles.toast}><Text>{message}</Text></View>; }
export function ConfirmDialog({ visible, title, description, onConfirm, onCancel }: { visible: boolean; title: string; description?: string; onConfirm: () => void; onCancel: () => void }) { return <Modal visible={visible} transparent accessibilityViewIsModal><View style={styles.scrim}><View style={styles.dialog} accessibilityRole="alert" aria-modal={true}><Text accessibilityRole="header" style={styles.stateTitle}>{title}</Text>{description && <Text>{description}</Text>}<View style={styles.actions}><Button label="Cancel" variant="secondary" onPress={onCancel} /><Button label="Confirm" variant="danger" onPress={onConfirm} /></View></View></View></Modal>; }
export function Skeleton({ width = "100%", height = 20 }: { width?: DimensionValue; height?: number }) { const { theme } = useTheme(); return <View testID="skeleton" accessibilityLabel="Loading content" style={{ width, height, backgroundColor: theme.colors.border, borderRadius: theme.radii.sm }} />; }
export function RecipeMedia({ title, tags = [] }: { title: string; tags?: string[] }) { const initials = title.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join("").toUpperCase() || "R"; const seed = `${title}${tags.join("")}`.split("").reduce((sum, char) => sum + char.charCodeAt(0), 0); const colors = ["#b7e4c7", "#f6bd60", "#f4a3a3", "#a9d6e5"]; return <View testID="recipe-media" accessibilityRole="image" accessibilityLabel={`${title} recipe placeholder`} style={[styles.media, { backgroundColor: colors[seed % colors.length] }]}><Text style={styles.mediaText}>{initials}</Text></View>; }

const styles = StyleSheet.create({ button: { minHeight: 44, minWidth: 44, borderWidth: 1, borderRadius: 12, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, iconButton: { width: 44, paddingHorizontal: 0 }, buttonText: { fontWeight: "600" }, field: { gap: 8, marginBottom: 16 }, label: { fontSize: 15, fontWeight: "600" }, hint: { color: "#527060", fontSize: 12 }, error: { color: "#b42318" }, textarea: { minHeight: 120, borderWidth: 1, borderColor: "#d0e5d6", borderRadius: 8, padding: 12, fontSize: 15 }, screen: { flexGrow: 1, alignItems: "center" }, readable: { width: "100%" }, pageHeader: { flexDirection: "row", alignItems: "center", gap: 16, marginBottom: 24 }, heading: { fontWeight: "700" }, sectionTitle: { fontSize: 18, fontWeight: "700", marginBottom: 12 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 16 }, notice: { minHeight: 44, padding: 12, borderWidth: 1, borderRadius: 8, justifyContent: "center" }, state: { minHeight: 44, padding: 16, alignItems: "center", justifyContent: "center", gap: 8 }, stateTitle: { fontSize: 18, fontWeight: "700" }, badge: { minHeight: 44, minWidth: 44, paddingHorizontal: 12, borderWidth: 1, borderRadius: 999, alignItems: "center", justifyContent: "center" }, rating: { flexDirection: "row" }, ratingButton: { minWidth: 44, minHeight: 44, alignItems: "center", justifyContent: "center" }, toast: { minHeight: 44, padding: 12, borderRadius: 8, backgroundColor: "#10231c" }, scrim: { flex: 1, backgroundColor: "rgba(16,35,28,.48)", alignItems: "center", justifyContent: "center", padding: 24 }, dialog: { width: "100%", maxWidth: 480, gap: 16, padding: 24, borderRadius: 16, backgroundColor: "#fff" }, actions: { flexDirection: "row", justifyContent: "flex-end", gap: 8 }, media: { minHeight: 160, alignItems: "center", justifyContent: "center", borderRadius: 16 }, mediaText: { fontSize: 36, fontWeight: "800", color: "#10231c" } });
